#配置数据源
spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      #url: jdbc:log4jdbc:mysql://${DB_HOST:59.110.71.115}:${DB_PORT:3306}/${DB_NAME:eladmin}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      url: jdbc:log4jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:eladmin}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: ${DB_USER:root}
      #password: ${DB_PWD:mina}
      password: ${DB_PWD:123456}
      # 初始连接数
      initial-size: 5
      # 最小连接数
      min-idle: 10
      # 最大连接数
      max-active: 20
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 连接在池中最大生存的时间
      max-evictable-idle-time-millis: 900000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 检测连接是否有效
      validation-query: select 1
      # 配置监控统计
      webStatFilter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
      filter:
        stat:
          enabled: true
          # 记录慢SQL
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    #数据库索引
    database: ${REDIS_DB:0}
    #host: ${REDIS_HOST:59.110.71.115}
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:Dragon!@#123}
    #连接超时时间
    timeout: 5000

# 登录相关配置
login:
  # 是否登录缓存
  cache-enable: true
  # 是否限制单用户登录
  single-login: false
  # 验证码
  login-code:
    # 验证码类型配置 查看 LoginCodeEnum 类
    code-type: arithmetic
    # 验证码宽度
    width: 111
    #  验证码高度
    heigth: 36
    # 字体名称，为空则使用默认字体
    font-name:
    # 字体大小
    font-size: 25
    # 内容长度
    length: 2
    # 登录图形验证码有效时间/分钟
    expiration: 2

# jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token-
  # 验证码
  code-key: code-key-
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000

#是否开启swagger-ui
swagger:
  enabled: true

#是否允许生成代码，生产环境设置为false
generator:
  enabled: true

# IP 本地解析
ip:
  local-parsing: true

# 文件存储路径
file:
  mac:
    path: ~/file/
    avatar: ~/avatar/
  linux:
    path: /home/dragonadmin/file/
    avatar: /home/dragonadmin/avatar/
  windows:
    path: E:\dragonadmin\file\
    avatar: E:\dragonadmin\avatar\
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5

#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  #public_key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC9ywMeCx0B/RlyEYvOZJ0RPFIZipgZK8urD84hpXkMM/NdSklNn5IgpUsOtWyRdxcTJYnQg0Rk389UIQiWFcuoPDW4luLZQMXAxtmVp4KBlaxAHI2bDUUXIBb69BFYYm1fJXjQPt5DU+RpYPlci+S/Y49zMAHCLAx7ohKuDpfaNQIDAQAB
  private_key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAL3LAx4LHQH9GXIRi85knRE8UhmKmBkry6sPziGleQwz811KSU2fkiClSw61bJF3FxMlidCDRGTfz1QhCJYVy6g8NbiW4tlAxcDG2ZWngoGVrEAcjZsNRRcgFvr0EVhibV8leNA+3kNT5Glg+VyL5L9jj3MwAcIsDHuiEq4Ol9o1AgMBAAECgYEAq04e/TIIt6/MFNJTfzH/NvxcGiOnTyjhhwAYDPR/Qo1tfum7Ki36Ri8LhTYpzU5RbH24W5Tv2aDNUOEUD+uSSjQrm6PmVP4X7MB2RU+oZ6+xYxEvxHQJ953PUm9w2AUhW4MXZIdf5EF2N7GH+cI9dvqEG9phXwUVO26WNzX9+A0CQQDiIC+SRsAohtx2MvnWdtwqsSAmo+9LkFTDtGQLP+lTRE77DFe+/jAmtq0yGL4lK6PGJj9JoDi/eHQsx83UIhpjAkEA1t4D5Nb8f9XWDauDU3sod2SFE4PvfKjATUS9Z+kEo8PxN0lGUNkYiGAgeciiD8Xoj3U3Ci3kVMLwmGwk7j9QhwJABCaZGPNJhbTsCRNoeKJX6kS0FWF+/AEbPThrebVjoA6p8HvKhIv/8EX8KeZAX0hMyk9bbAuP3xvj7gqA4br6hwJANzUuXPMcR6Bi8no6MQ349MxgIQaKV0ZourHJ1NQbfBSRevoZ1hYh5pCEZ6Y0dccNHScp8DSgcWLxPMi0qH6eKwJBAIFNugGBz8UY1x1YEyPlbB2lOUGTzverFDb8rFkUqGXKvxE8jaUMKxqPwfR+ggHCLDGjP2XLZ/CjZaCJg5bZ/tg=