# 设置端口
server:
  port: 8000

# 设置环境
spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50